#ifndef ASR_CORE_FOREIGNINTERFACEHOST_FOREIGNINTERFACEHOSTENUM_H
#define ASR_CORE_FOREIGNINTERFACEHOST_FOREIGNINTERFACEHOSTENUM_H

#include <AutoStarRail/Core/ForeignInterfaceHost/Config.h>

ASR_CORE_FOREIGNINTERFACEHOST_NS_BEGIN

enum class ForeignInterfaceLanguage
{
    Python,
    CSharp,
    Java,
    Cpp,
    Lua
};

ASR_CORE_FOREIGNINTERFACEHOST_NS_END

#endif // ASR_CORE_FOREIGNINTERFACEHOST_FOREIGNINTERFACEHOSTENUM_H
